// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opc.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace OpcPackage {
  /// <summary>
  ///  The greeting service definition.
  /// </summary>
  public static class Greeter
  {
    static readonly string __ServiceName = "opcPackage.Greeter";

    static readonly Marshaller<global::OpcPackage.HelloRequest> __Marshaller_HelloRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::OpcPackage.HelloRequest.Parser.ParseFrom);
    static readonly Marshaller<global::OpcPackage.HelloReply> __Marshaller_HelloReply = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::OpcPackage.HelloReply.Parser.ParseFrom);
    static readonly Marshaller<global::OpcPackage.SumRequest> __Marshaller_SumRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::OpcPackage.SumRequest.Parser.ParseFrom);
    static readonly Marshaller<global::OpcPackage.SumReply> __Marshaller_SumReply = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::OpcPackage.SumReply.Parser.ParseFrom);
    static readonly Marshaller<global::OpcPackage.GroupResponseModelRpc_Request> __Marshaller_GroupResponseModelRpc_Request = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::OpcPackage.GroupResponseModelRpc_Request.Parser.ParseFrom);
    static readonly Marshaller<global::OpcPackage.ServerReply> __Marshaller_ServerReply = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::OpcPackage.ServerReply.Parser.ParseFrom);

    static readonly Method<global::OpcPackage.HelloRequest, global::OpcPackage.HelloReply> __Method_SayHello = new Method<global::OpcPackage.HelloRequest, global::OpcPackage.HelloReply>(
        MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_HelloRequest,
        __Marshaller_HelloReply);

    static readonly Method<global::OpcPackage.HelloRequest, global::OpcPackage.HelloReply> __Method_SayHelloAgain = new Method<global::OpcPackage.HelloRequest, global::OpcPackage.HelloReply>(
        MethodType.Unary,
        __ServiceName,
        "SayHelloAgain",
        __Marshaller_HelloRequest,
        __Marshaller_HelloReply);

    static readonly Method<global::OpcPackage.SumRequest, global::OpcPackage.SumReply> __Method_MySum = new Method<global::OpcPackage.SumRequest, global::OpcPackage.SumReply>(
        MethodType.Unary,
        __ServiceName,
        "MySum",
        __Marshaller_SumRequest,
        __Marshaller_SumReply);

    static readonly Method<global::OpcPackage.GroupResponseModelRpc_Request, global::OpcPackage.ServerReply> __Method_ReceiveGroupTags = new Method<global::OpcPackage.GroupResponseModelRpc_Request, global::OpcPackage.ServerReply>(
        MethodType.Unary,
        __ServiceName,
        "ReceiveGroupTags",
        __Marshaller_GroupResponseModelRpc_Request,
        __Marshaller_ServerReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::OpcPackage.OpcReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Greeter</summary>
    public abstract class GreeterBase
    {
      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::OpcPackage.HelloReply> SayHello(global::OpcPackage.HelloRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::OpcPackage.HelloReply> SayHelloAgain(global::OpcPackage.HelloRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::OpcPackage.SumReply> MySum(global::OpcPackage.SumRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::OpcPackage.ServerReply> ReceiveGroupTags(global::OpcPackage.GroupResponseModelRpc_Request request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Greeter</summary>
    public class GreeterClient : ClientBase<GreeterClient>
    {
      /// <summary>Creates a new client for Greeter</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GreeterClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Greeter that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GreeterClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GreeterClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GreeterClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual global::OpcPackage.HelloReply SayHello(global::OpcPackage.HelloRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHello(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual global::OpcPackage.HelloReply SayHello(global::OpcPackage.HelloRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
      }
      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual AsyncUnaryCall<global::OpcPackage.HelloReply> SayHelloAsync(global::OpcPackage.HelloRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHelloAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual AsyncUnaryCall<global::OpcPackage.HelloReply> SayHelloAsync(global::OpcPackage.HelloRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
      }
      public virtual global::OpcPackage.HelloReply SayHelloAgain(global::OpcPackage.HelloRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHelloAgain(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::OpcPackage.HelloReply SayHelloAgain(global::OpcPackage.HelloRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHelloAgain, null, options, request);
      }
      public virtual AsyncUnaryCall<global::OpcPackage.HelloReply> SayHelloAgainAsync(global::OpcPackage.HelloRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHelloAgainAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::OpcPackage.HelloReply> SayHelloAgainAsync(global::OpcPackage.HelloRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHelloAgain, null, options, request);
      }
      public virtual global::OpcPackage.SumReply MySum(global::OpcPackage.SumRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return MySum(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::OpcPackage.SumReply MySum(global::OpcPackage.SumRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_MySum, null, options, request);
      }
      public virtual AsyncUnaryCall<global::OpcPackage.SumReply> MySumAsync(global::OpcPackage.SumRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return MySumAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::OpcPackage.SumReply> MySumAsync(global::OpcPackage.SumRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_MySum, null, options, request);
      }
      public virtual global::OpcPackage.ServerReply ReceiveGroupTags(global::OpcPackage.GroupResponseModelRpc_Request request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ReceiveGroupTags(request, new CallOptions(headers, deadline, cancellationToken));
      }

        public virtual global::OpcPackage.ServerReply ReceiveGroupTags(
            global::OpcPackage.GroupResponseModelRpc_Request request, CallOptions options)
        {
            return CallInvoker.BlockingUnaryCall(__Method_ReceiveGroupTags, null, options, request);
            //try
            //{
            //    return CallInvoker.BlockingUnaryCall(__Method_ReceiveGroupTags, null, options, request);
            //}
            //catch (Exception ex)
            //{
            //    return new ServerReply() {Message = ex.Message};
            //}
        }

        public virtual AsyncUnaryCall<global::OpcPackage.ServerReply> ReceiveGroupTagsAsync(global::OpcPackage.GroupResponseModelRpc_Request request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ReceiveGroupTagsAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::OpcPackage.ServerReply> ReceiveGroupTagsAsync(global::OpcPackage.GroupResponseModelRpc_Request request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ReceiveGroupTags, null, options, request);
      }
      protected override GreeterClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GreeterClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(GreeterBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHello, serviceImpl.SayHello)
          .AddMethod(__Method_SayHelloAgain, serviceImpl.SayHelloAgain)
          .AddMethod(__Method_MySum, serviceImpl.MySum)
          .AddMethod(__Method_ReceiveGroupTags, serviceImpl.ReceiveGroupTags).Build();
    }

  }
}
#endregion
